import { HospitalData, Notification } from "./interfaces"

export const mockOTData = {
  theaters: [
    {
      id: "OT-01",
      name: "Operating Theater 1",
      status: "occupied",
      currentSurgery: {
        patient: "Rajesh Kumar",
        procedure: "Cardiac Bypass Surgery",
        surgeon: "Dr. Sharath Kumar",
        startTime: "08:00 AM",
        estimatedDuration: "4 hours",
        elapsed: "2.5 hours",
        progress: 62,
      },
      nextSurgery: {
        patient: "Priya Sharma",
        procedure: "Appendectomy",
        scheduledTime: "02:00 PM",
      },
    },
    {
      id: "OT-02",
      name: "Operating Theater 2",
      status: "available",
      lastCleaned: "11:30 AM",
      nextSurgery: {
        patient: "Mohammed Ali",
        procedure: "Orthopedic Surgery",
        scheduledTime: "01:00 PM",
      },
    },
    {
      id: "OT-03",
      name: "Operating Theater 3",
      status: "maintenance",
      maintenanceType: "Equipment Calibration",
      estimatedCompletion: "03:00 PM",
    },
    {
      id: "OT-04",
      name: "Operating Theater 4",
      status: "occupied",
      currentSurgery: {
        patient: "Lakshmi Devi",
        procedure: "Cataract Surgery",
        surgeon: "Dr. Priya Nair",
        startTime: "10:30 AM",
        estimatedDuration: "1.5 hours",
        elapsed: "1 hour",
        progress: 67,
      },
    },
    {
      id: "OT-05",
      name: "Operating Theater 5",
      status: "cleaning",
      cleaningStarted: "11:45 AM",
      estimatedCompletion: "12:30 PM",
    },
    {
      id: "OT-06",
      name: "Operating Theater 6",
      status: "available",
      lastCleaned: "10:00 AM",
      nextSurgery: {
        patient: "Suresh Babu",
        procedure: "Hernia Repair",
        scheduledTime: "04:00 PM",
      },
    },
  ],
  todaySchedule: [
    {
      id: 1,
      time: "08:00 AM",
      patient: "Rajesh Kumar",
      procedure: "Cardiac Bypass Surgery",
      surgeon: "Dr. Sharath Kumar",
      theater: "OT-01",
      duration: "4 hours",
      status: "in-progress",
    },
    {
      id: 2,
      time: "10:30 AM",
      patient: "Lakshmi Devi",
      procedure: "Cataract Surgery",
      surgeon: "Dr. Priya Nair",
      theater: "OT-04",
      duration: "1.5 hours",
      status: "in-progress",
    },
    {
      id: 3,
      time: "01:00 PM",
      patient: "Mohammed Ali",
      procedure: "Orthopedic Surgery",
      surgeon: "Dr. Rajesh Menon",
      theater: "OT-02",
      duration: "3 hours",
      status: "scheduled",
    },
    {
      id: 4,
      time: "02:00 PM",
      patient: "Priya Sharma",
      procedure: "Appendectomy",
      surgeon: "Dr. Sharath Kumar",
      theater: "OT-01",
      duration: "2 hours",
      status: "scheduled",
    },
    {
      id: 5,
      time: "04:00 PM",
      patient: "Suresh Babu",
      procedure: "Hernia Repair",
      surgeon: "Dr. Priya Nair",
      theater: "OT-06",
      duration: "2.5 hours",
      status: "scheduled",
    },
  ],
  emergencyQueue: [
    {
      id: 1,
      patient: "Emergency Patient 1",
      condition: "Trauma - Multiple Fractures",
      priority: "critical",
      waitTime: "15 min",
      estimatedDuration: "3 hours",
    },
    {
      id: 2,
      patient: "Emergency Patient 2",
      condition: "Acute Appendicitis",
      priority: "urgent",
      waitTime: "45 min",
      estimatedDuration: "1.5 hours",
    },
  ],
}

export const mockPatients = [
  {
    id: "P001",
    name: "Rajesh Kumar",
    age: 45,
    gender: "Male",
    phone: "+91 98765 43210",
    address: "123 MG Road, Mangalore",
    condition: "Hypertension",
    status: "Stable",
    lastVisit: "2025-06-03",
    nextAppointment: "2025-06-10",
    vitals: {
      bp: "140/90",
      pulse: "78 bpm",
      temp: "98.6°F",
      weight: "75 kg",
      height: "170 cm",
    },
    medications: [{
      id: "med1",
      name: "Paracetamol",
      dosage: "500mg",
      frequency: "Twice a day",
      duration: "5 days",
      instructions: "After food",
      drugInfo: {
        id: "drug1",
        currentStock: 100,
        minStock: 20,
        status: "available",
        category: "analgesic",
        batchNumber: "B12345",
        expiryDate: new Date("2025-12-31"),
      }
    },],
    allergies: ["Penicillin"],
    medicalHistory: [
      { date: "2025-06-03", diagnosis: "Hypertension follow-up", treatment: "Medication adjustment" },
      { date: "2025-05-20", diagnosis: "Routine check-up", treatment: "Blood pressure monitoring" },
      { date: "2025-04-15", diagnosis: "Initial hypertension diagnosis", treatment: "Lifestyle counseling" },
    ],
  },
  {
    id: "P002",
    name: "Priya Sharma",
    age: 32,
    gender: "Female",
    phone: "+91 87654 32109",
    address: "456 Car Street, Mangalore",
    condition: "Pregnancy - 28 weeks",
    status: "Normal",
    lastVisit: "2025-06-01",
    nextAppointment: "2025-06-08",
    vitals: {
      bp: "110/70",
      pulse: "85 bpm",
      temp: "98.4°F",
      weight: "68 kg",
      height: "162 cm",
    },
    medications: ["Folic Acid", "Iron supplements"],
    allergies: ["None known"],
    medicalHistory: [
      { date: "2025-06-01", diagnosis: "Prenatal check-up", treatment: "Routine monitoring" },
      { date: "2025-05-15", diagnosis: "Prenatal check-up", treatment: "Ultrasound normal" },
      { date: "2025-04-30", diagnosis: "Prenatal check-up", treatment: "Blood tests normal" },
    ],
  },
  {
    id: "P003",
    name: "Mohammed Ali",
    age: 28,
    gender: "Male",
    phone: "+91 76543 21098",
    address: "789 Lighthouse Hill, Mangalore",
    condition: "Fractured Radius",
    status: "Recovering",
    lastVisit: "2025-06-02",
    nextAppointment: "2025-06-09",
    vitals: {
      bp: "120/80",
      pulse: "72 bpm",
      temp: "98.2°F",
      weight: "70 kg",
      height: "175 cm",
    },
    medications: ["Ibuprofen 400mg", "Calcium supplements"],
    allergies: ["Aspirin"],
    medicalHistory: [
      { date: "2025-06-02", diagnosis: "Fracture follow-up", treatment: "X-ray shows healing" },
      { date: "2025-05-25", diagnosis: "Cast application", treatment: "Plaster cast applied" },
      { date: "2025-05-20", diagnosis: "Radius fracture", treatment: "Emergency treatment" },
    ],
  },
  {
    id: "P004",
    name: "Lakshmi Devi",
    age: 56,
    gender: "Female",
    phone: "+91 65432 10987",
    address: "321 Kadri Hills, Mangalore",
    condition: "Type 2 Diabetes",
    status: "Controlled",
    lastVisit: "2025-05-30",
    nextAppointment: "2025-06-13",
    vitals: {
      bp: "130/85",
      pulse: "68 bpm",
      temp: "98.0°F",
      weight: "65 kg",
      height: "158 cm",
    },
    medications: ["Metformin 500mg", "Glimepiride 2mg"],
    allergies: ["Sulfa drugs"],
    medicalHistory: [
      { date: "2025-05-30", diagnosis: "Diabetes management", treatment: "HbA1c: 7.2%" },
      { date: "2025-05-15", diagnosis: "Routine follow-up", treatment: "Blood sugar monitoring" },
      { date: "2025-04-30", diagnosis: "Medication adjustment", treatment: "Dosage increased" },
    ],
  },
]

export const mockDoctorData = {
  appointments: [
    { id: 1, patient: "Rajesh Kumar", time: "09:30 AM", status: "Completed", type: "Follow-up" },
    { id: 2, patient: "Priya Sharma", time: "10:15 AM", status: "In Progress", type: "Consultation" },
    { id: 3, patient: "Mohammed Ali", time: "11:00 AM", status: "Waiting", type: "New Patient" },
    { id: 4, patient: "Lakshmi Devi", time: "11:45 AM", status: "Scheduled", type: "Follow-up" },
    { id: 5, patient: "Suresh Babu", time: "02:30 PM", status: "Scheduled", type: "Surgery Prep" },
  ],
  patients: [
    { id: "P001", name: "Rajesh Kumar", age: 45, gender: "Male", condition: "Hypertension", lastVisit: "2 days ago" },
    { id: "P002", name: "Priya Sharma", age: 32, gender: "Female", condition: "Pregnancy", lastVisit: "1 week ago" },
    { id: "P003", name: "Mohammed Ali", age: 28, gender: "Male", condition: "Fracture", lastVisit: "New Patient" },
    { id: "P004", name: "Lakshmi Devi", age: 56, gender: "Female", condition: "Diabetes", lastVisit: "3 days ago" },
  ],
  alerts: [
    { id: 1, message: "Lab results ready for Rajesh Kumar", time: "5 min ago", type: "info" },
    { id: 2, message: "Medication approval needed for Priya Sharma", time: "15 min ago", type: "warning" },
    { id: 3, message: "OT 2 scheduled for 2:30 PM", time: "30 min ago", type: "info" },
  ],
}

export const demoCredentials = {
  admin: { username: "admin", password: "admin123" },
  doctor: { username: "dr.smith", password: "doctor123" },
  nurse: { username: "nurse.jane", password: "nurse123" },
  technician: { username: "tech.mike", password: "tech123" },
  pharmacist: { username: "pharm.sarah", password: "pharma123" },
}

export const mockNurseData = {
  patients: [
    {
      id: "P001",
      name: "Rajesh Kumar",
      age: 45,
      bed: "W3-12",
      condition: "Stable",
      vitals: { temp: "98.6°F", bp: "120/80", pulse: "72 bpm", spo2: "98%" },
    },
    {
      id: "P002",
      name: "Priya Sharma",
      age: 32,
      bed: "W3-14",
      condition: "Improving",
      vitals: { temp: "99.1°F", bp: "118/76", pulse: "80 bpm", spo2: "97%" },
    },
    {
      id: "P003",
      name: "Mohammed Ali",
      age: 28,
      bed: "W3-16",
      condition: "Critical",
      vitals: { temp: "101.2°F", bp: "140/90", pulse: "92 bpm", spo2: "94%" },
    },
    {
      id: "P004",
      name: "Lakshmi Devi",
      age: 56,
      bed: "W3-18",
      condition: "Stable",
      vitals: { temp: "98.2°F", bp: "130/85", pulse: "68 bpm", spo2: "99%" },
    },
  ],
  medications: [
    {
      id: 1,
      patient: "Rajesh Kumar",
      medication: "Atenolol 50mg",
      time: "10:00 AM",
      status: "Administered",
      notes: "Given with water",
    },
    {
      id: 2,
      patient: "Priya Sharma",
      medication: "Paracetamol 500mg",
      time: "10:30 AM",
      status: "Due",
      notes: "Check temperature before administering",
    },
    {
      id: 3,
      patient: "Mohammed Ali",
      medication: "Ceftriaxone 1g IV",
      time: "11:00 AM",
      status: "Due",
      notes: "Doctor to be present",
    },
    {
      id: 4,
      patient: "Lakshmi Devi",
      medication: "Insulin 10 units",
      time: "11:30 AM",
      status: "Due",
      notes: "Check blood sugar first",
    },
  ],
  tasks: [
    { id: 1, task: "Change IV for Mohammed Ali", priority: "high", time: "10:45 AM", completed: false },
    { id: 2, task: "Record vitals for all patients", priority: "medium", time: "11:00 AM", completed: false },
    { id: 3, task: "Assist Dr. Kumar with rounds", priority: "medium", time: "11:30 AM", completed: false },
    { id: 4, task: "Prepare discharge papers for Bed W3-10", priority: "low", time: "12:00 PM", completed: false },
    { id: 5, task: "Restock ward supplies", priority: "low", time: "02:00 PM", completed: false },
  ],
}

export const mockPharmacistData = {
  inventory: [
    { id: 1, name: "Paracetamol 500mg", stock: 2500, minStock: 500, status: "available", category: "Analgesic" },
    { id: 2, name: "Amoxicillin 250mg", stock: 150, minStock: 200, status: "low", category: "Antibiotic" },
    { id: 3, name: "Insulin Injection", stock: 45, minStock: 100, status: "critical", category: "Hormone" },
    { id: 4, name: "Aspirin 75mg", stock: 1800, minStock: 300, status: "available", category: "Antiplatelet" },
    { id: 5, name: "Atenolol 50mg", stock: 320, minStock: 200, status: "available", category: "Beta Blocker" },
    { id: 6, name: "Diazepam 5mg", stock: 120, minStock: 150, status: "low", category: "Sedative" },
  ],
  prescriptions: [
    {
      id: "RX001",
      patient: "Rajesh Kumar",
      doctor: "Dr. Sharath Kumar",
      items: [
        { name: "Paracetamol 500mg", dosage: "1-0-1", days: 5 },
        { name: "Amoxicillin 250mg", dosage: "1-1-1", days: 7 },
      ],
      status: "pending",
      time: "10:15 AM",
    },
    {
      id: "RX002",
      patient: "Priya Sharma",
      doctor: "Dr. Priya Nair",
      items: [
        { name: "Aspirin 75mg", dosage: "0-1-0", days: 30 },
        { name: "Atenolol 50mg", dosage: "1-0-0", days: 30 },
      ],
      status: "processing",
      time: "09:45 AM",
    },
    {
      id: "RX003",
      patient: "Mohammed Ali",
      doctor: "Dr. Rajesh Menon",
      items: [{ name: "Diazepam 5mg", dosage: "0-0-1", days: 10 }],
      status: "completed",
      time: "09:30 AM",
    },
  ],
  orders: [
    {
      id: "PO001",
      supplier: "MedSupply Ltd",
      items: [
        { name: "Amoxicillin 250mg", quantity: 500 },
        { name: "Insulin Injection", quantity: 200 },
      ],
      status: "ordered",
      date: "2025-06-03",
    },
    {
      id: "PO002",
      supplier: "PharmaCare Inc",
      items: [{ name: "Diazepam 5mg", quantity: 300 }],
      status: "shipped",
      date: "2025-06-01",
    },
    {
      id: "PO003",
      supplier: "MediTech Solutions",
      items: [
        { name: "Paracetamol 500mg", quantity: 1000 },
        { name: "Aspirin 75mg", quantity: 500 },
      ],
      status: "delivered",
      date: "2025-05-28",
    },
  ],
}

export const mockTechnicianData = {
  displays: [
    {
      id: 1,
      location: "Main Lobby",
      status: "online",
      uptime: "99.8%",
      lastUpdate: "2 min ago",
      content: "Queue Display",
    },
    {
      id: 2,
      location: "OT Complex",
      status: "online",
      uptime: "98.5%",
      lastUpdate: "1 min ago",
      content: "Surgery Status",
    },
    {
      id: 3,
      location: "Cardiology Wing",
      status: "offline",
      uptime: "95.2%",
      lastUpdate: "15 min ago",
      content: "Department Info",
    },
    {
      id: 4,
      location: "Pharmacy",
      status: "online",
      uptime: "99.1%",
      lastUpdate: "3 min ago",
      content: "Drug Inventory",
    },
    {
      id: 5,
      location: "Emergency Ward",
      status: "warning",
      uptime: "97.8%",
      lastUpdate: "8 min ago",
      content: "Emergency Alerts",
    },
    { id: 6, location: "ICU", status: "online", uptime: "99.9%", lastUpdate: "1 min ago", content: "Patient Status" },
    {
      id: 7,
      location: "Pediatrics",
      status: "online",
      uptime: "98.9%",
      lastUpdate: "4 min ago",
      content: "Department Info",
    },
    {
      id: 8,
      location: "Maternity Ward",
      status: "maintenance",
      uptime: "96.5%",
      lastUpdate: "30 min ago",
      content: "Ward Info",
    },
  ],
  systemAlerts: [
    { id: 1, type: "Network", message: "Display #3 connection timeout", severity: "high", time: "15 min ago" },
    { id: 2, type: "Hardware", message: "Display #8 scheduled maintenance", severity: "medium", time: "30 min ago" },
    { id: 3, type: "Content", message: "Emergency alert broadcast successful", severity: "info", time: "45 min ago" },
    { id: 4, type: "Performance", message: "Network latency spike detected", severity: "low", time: "1 hour ago" },
  ],
  networkStats: {
    totalDisplays: 73,
    onlineDisplays: 68,
    offlineDisplays: 2,
    maintenanceDisplays: 3,
    networkUptime: "99.2%",
    avgResponseTime: "1.2s",
    dataTransferred: "2.4 GB",
    errorRate: "0.8%",
  },
}

export const CSV_URLS = {
  drugInventory: '/data/drug_inventory.csv',
  tokenQueue: '/data/token_queue.csv',
  departments: '/data/departments.csv',
  bloodBank: '/data/blood_bank.csv',
  emergencyAlerts: '/data/emergency_alerts.csv',
  otStatus: '/data/ot_status.csv'
}

export const commonMedications = [
  "Paracetamol 500mg",
  "Amoxicillin 250mg",
  "Aspirin 75mg",
  "Atenolol 50mg",
  "Metformin 500mg",
  "Amlodipine 5mg",
  "Omeprazole 20mg",
  "Ibuprofen 400mg",
]

export const mockNotifications: Notification[] = [
  {
    id: "1",
    type: "emergency",
    title: "Emergency Alert",
    message: "Code Blue - ICU Ward 3, Bed 12. Immediate assistance required.",
    time: "2 min ago",
    read: false,
    priority: "high",
  },
  {
    id: "2",
    type: "warning",
    title: "Medication Alert",
    message: "Low stock alert: Insulin injection - Only 45 units remaining",
    time: "15 min ago",
    read: false,
    priority: "medium",
  },
  {
    id: "3",
    type: "info",
    title: "Schedule Update",
    message: "Your 2:00 PM appointment with Priya Sharma has been confirmed",
    time: "30 min ago",
    read: true,
    priority: "low",
  },
  {
    id: "4",
    type: "success",
    title: "Lab Results",
    message: "Lab results for Rajesh Kumar are now available for review",
    time: "1 hour ago",
    read: false,
    priority: "medium",
  },
  {
    id: "5",
    type: "info",
    title: "System Maintenance",
    message: "Scheduled maintenance tonight from 11 PM to 2 AM",
    time: "2 hours ago",
    read: true,
    priority: "low",
  },
  {
    id: "6",
    type: "warning",
    title: "Display Offline",
    message: "Display #3 in Cardiology Wing is offline - Technical team notified",
    time: "3 hours ago",
    read: true,
    priority: "medium",
  },
]

export const DEFAULT_DATA: HospitalData = {
  drugInventory: [],
  tokenQueue: [],
  departments: [],
  bloodBank: [],
  emergencyAlerts: [],
  otStatus: []
}