name: pull requests

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  uneditable:
    uses: gaureshpai/cprm-prototype/.github/workflows/pull-requests.yml@main