name: update changelog

on:
  release:
    types: [released]

permissions: {}

jobs:
  update:
    permissions:
      contents: write
    uses: gaureshpai/cprm-prototype/.github/workflows/update-changelog.yml@main
